### PR TITLE
Add the ability to between kebab-case and snake_case

### LINKED ISSUE #218: Support for Kebab case?
**Is your feature request related to a problem? Please describe.**
#180 #151 

**Describe the solution you'd like**
Discussion: Should we add support for Kebab case? 
- [x] kebabize
- [x] dekebabize
- [x] is_kebabcase
- [x] type hints
- [ ] test cases

**Describe alternatives you've considered**
-

**Additional context**
-

### PR DESCRIPTION
**Pull request by pgjones**
## Status
**READY**

## Description
This can then be combined with the other functions to convert
kebab-case to any other supported case.

Note the character casing is preserved in conversion as I think this
makes the most sense. It can trivially be altered after using lower or
upper.

## Related Issues
Fixes #218 and #180

## Todos
- [x] Tests
- [x] Documentation

### CODE REVIEW

**Comment by ronnie-llamado** [comment]
@pgjones Can you rebase this PR when you get the chance? I anticipate it will pass; the workflow was just updated (#237).

**Comment by pgjones** [comment]
@ronnie-llamado I've just updated, thanks.

**Comment by nficano** [comment]
Can you please fix the coverage decrease?

**Comment by pgjones** [comment]
It looks like @grehnj took these changes and created #272 which was then merged. Will close.

**Pull request closed without merging**
